module.exports= {
    app_name : "Vis Viva",
    contact_email : "luxlunarislabs@gmail.com",
    contact_website : "https://aiman-al-masoud.github.io/",
    psittacus_website :"https://psittacus.eu.pythonanywhere.com" ,
    asset_credits_link : "../attribs.md",
    full_source_link : "...............",
    full_license_termns_link: "..........",
    psittacus: "Psittacus",
    help : "Help",
    login : "Login",
    settings : "Settings",
    welcome_back : "Welcome back",
    language : "Language",
    sounds : "Sounds",
    field_your_troops : "Field your troops!",
    player_vs_player : "Player vs Player",
    player_vs_compuer : "Player vs Computer",
    info : "Info",
    settings : "Settings",
    logout : "Logout",
    online_users : "Online Users",
    click_on_user_in_list: "Click on a user in the list to challenge them!",
    global_ranking : "Global Ranking",
    you_got_a_challenge_from : "You got a challenge from",
    accept : "Accept",
    game_over : "Game Over",
    ok : "Ok",
    you_won : "You Won!",
    you_lost : "You Lost!",
    your_opponent_left_the_game : "(Your Opponent Left the Game)",
    miss : "miss!",
    dodge : "dodge!",
    critical : "critical!",
    ready : "Ready, go!",
    health_stat : "Health",
    attack_stat : "Attack",
    dodge_stat : "Dodge",
    miss_stat : "Miss",
    critical_hit_rate_stat : "Critical",
    vis_viva_is : "Vis Viva is an online, multiplayer strategy game, taking inspiration from various sources.",
    invite_your_friends_and_challege_them :"Invite your friends and challenge them on an engrossing one-to-one PVP battle, where only one will be left to stand! Or try beating the server in PVC mode!",
    gameplay : "Gameplay",
    license : "License",
    credits : "Credits",
    privacy : "Privacy",
    other_links: "Other Links",
    the_rules_are_simple : "The rules are simple!",
    rule_1 : "When you challenge someone, an invite is sent, and you're taken to the battlefield; which you can field your troops in.",
    rule_2 : "After you're done fielding your troops, you can hit the red '"+"Ready, go!"+"' button.",
    rule_3 : "Your opponent will have received an invite, and may still be fielding his/her troops, so be patient...",
    rule_4 : "When your opponent's troops appear on the screen, you're all set! You get the first turn, by virtue of being the attacker.",
    rule_5 : "Blows are exchanged by selecting a battle unit in your half of the field, and then selecting your target on your oppoenent's half of the field.",
    you_can_play_with_mouse_or_keyboard : "You can play this game entirely using your mouse, or your keyboard.",
    depending_on_battle_units_there_can_be_misses: "Depending on what battle units you and your opponent chose, blows may miss, be dodged by the target, or land a critical hit!",
    wont_bother_you_any_further : "That's it, I won't bother you any further, go ahead and give it a go!",
    short_license_notice : "Vis Viva is free software, licensed under GPLv3.",
    see_full_license_terms : "See the full terms of the license here",
    get_the_source_code : "Get the source code",
    assets_credits_are_here : "Assets (images, sounds) come from several sources, they're all carefully linked here (together with their respective authors, when possible).",
    privacy_notice : "I don't collect any personal data on the users, except for their usernames and the history of their scores, which counts as legitimate usage.",
    liked_the_game_have_ideas : "Liked the game? Do you want to see more similar games? Do you have any game ideas to share? Contact me at",
    my_other_projects : "my other projects",
    and_especially_this_one : "and especially this one",
    please_check_out : "Please check out",
    samurai_description : "A skilled warrior is he indeed. Woe to whose poor flesh is touched by his dreadsome katana.",
    master_description : "He's the old wise master, many a great lesson he has taught, and many more he will teach...",
    fire_worm_description : "It hails from the far away land of the enchanted social elevator: when it was a juvenile worm, it dreamed of becoming a fire-spitting dragon.",
    king_bourouf_description : "The last descendent of an forgotten dynasty, that ruled the land with an iron fist, and spoke with a thick accent: his sword is just as heavy as that.",
    mushroom_description : "'Tis the murderous abomination that lurks in the forest. Its poisonous cap is as deadly as its venomous fangs."



}