module.exports= {
    app_name : "Vis Viva", 
    contact_email : "luxlunarislabs@gmail.com",
    contact_website : "https://aiman-al-masoud.github.io/",
    psittacus_website :"https://psittacus.eu.pythonanywhere.com" ,
    asset_credits_link : "../attribs.md",
    full_source_link : "...............",
    full_license_termns_link: "..........",
    psittacus: "Psittacus",
    help : "Aiuto",
    login : "Entra",
    settings : "Impostazioni",
    welcome_back : "Benvenuto/a",
    language : "Lingua",
    sounds : "Suoni",
    field_your_troops : "Disponi le tue truppe!",
    player_vs_player : "Giocatore contro Giocatore",
    player_vs_compuer : "Giocatore contro Computer",
    info : "Info",
    settings : "Impostazioni",
    logout : "Esci",
    online_users : "Utenti Connessi",
    click_on_user_in_list: "Clicca su un utente nella lista per sfidarlo!",
    global_ranking : "Classifica Globale",
    you_got_a_challenge_from : "Sei stato sfidato da",
    accept : "Accetta",
    game_over : "Game Over",
    ok : "Ok",
    you_won : "Hai vinto!",
    you_lost : "Hai perso!",
    your_opponent_left_the_game : "(Il tuo avversario ha abbandonato la partita)",
    miss : "mancato!",
    dodge : "schivata!",
    critical : "critico!",
    ready : "Pronto, via!",
    health_stat : "Vita",
    attack_stat : "Attacco",
    dodge_stat : "Schivata",
    miss_stat : "Inaccuratezza",
    critical_hit_rate_stat : "Critico",
    vis_viva_is : "Vis Viva è un videogioco di strategia multigiocatore, che trae ispirazione da varie fonti.",
    invite_your_friends_and_challege_them :"Invita i tuoi amici e sfidali ad un avvincente duello in PVP! O prova a battere il server in modalità PVC!",
    gameplay : "Regole",
    license : "Licenza",
    credits : "Crediti",
    privacy : "Privacy/Riservatezza",
    other_links: "Altri Collegamenti",
    the_rules_are_simple : "Le regole sono semplici!",
    rule_1 : "Quando sfidi qualcuno, un invito viene spedito, e tu vieni portato al campo di battaglia, in cui puoi posizionare le tue truppe!",
    rule_2 : "Quando hai finito di posizionare le truppe, clicca sul bottone rosso 'Pronto, via!' in alto a destra.",
    rule_3 : "Il tuo avversario avrà già ricevuto un invito, ma potrebbe essere ancora impegnato a posizionare le sue truppe, sii paziente...",
    rule_4 : "Quando le truppe del tuo avversario faranno capolino sul tuo schermo, potrai giocare! Toccherà a te per primo, in virtù di attaccante.",
    rule_5 : "I colpi sono scambiati selezionando un'unità nella tua metà del campo, e poi selezionando la vittima sulla metà del campo avversario.",
    you_can_play_with_mouse_or_keyboard : "Puoi giocare al gioco interamente usando il mouse, o la tastiera.",
    depending_on_battle_units_there_can_be_misses: "In funzione di quali truppe avete scelto tu e il tuo avversario, i colpi potrebbero mancare, essere schivati o recepiti come colpi critici!",
    wont_bother_you_any_further : "Questo è tutto, non ti tedierò più con le regole, è ora di provare il gioco!",
    short_license_notice : "Vis Viva è software libero, distribuito sotto licenza GPLv3.",
    see_full_license_terms : "Visualizza i termini completi della licenza",
    get_the_source_code : "Ottieni il codice sorgente",
    assets_credits_are_here : "Le risorse (immagini, suoni) provengono da fonti disparate, tutte attentamente linkate  (assieme a un riferimento all'autore, quando possibile).",
    privacy_notice : "Non raccolgo nessun dato personale sugli utenti, tranne i loro username e i loro punteggi, solo al legittimo scopo di rendere il gioco giocabile.",
    liked_the_game_have_ideas : "Ti è piaciuto il gioco? Ne vuoi vedere altri simili? Hai nuove idee da proporre? Contattami a",
    my_other_projects : "i miei altri progetti",
    and_especially_this_one : "e specialmente questo",
    please_check_out : "Dai un'occhiata a",
    samurai_description : "Un formidabile guerriero. Guai a colui la cui povera pelle è sfiorata dalla sua temibile katana.",
    master_description : "Il saggio e vetusto maestro. Tante grandi lezioni insegnò, e tante ancora ne insegnerà...",
    fire_worm_description : "Arriva dalla landa dell'ascensore sociale incantato: da giovane verme, sognava di diventare un dragone sputafuoco.",
    king_bourouf_description : "L'ultimo discendente di una dinastia caduta in oblio, che da secoli regnava con un pugno di ferro, e un accento accentuato: la sua lama è pesante quanto quest'utlimo.",
    mushroom_description : "È l'abominazione omicida che infesta la foresta. Il suo velenoso cappello è deleterio quanto le sue venefiche fauci."

}