module.exports= {
    app_name : "Vis Viva", 
    help : "Aiuto",
    login : "Entra",
    settings : "Impostazioni",
    welcome_back : "Benvenuto/a",
    language : "Lingua",
    sounds : "Suoni",
    field_your_troops : "Disponi le tue truppe!",
    player_vs_player : "Giocatore contro Giocatore",
    player_vs_compuer : "Giocatore contro Computer",
    info : "Info",
    settings : "Impostazioni",
    logout : "Esci",
    online_users : "Utenti Connessi",
    click_on_user_in_list: "Clicca su un utente nella lista per sfidarlo!",
    global_ranking : "Classifica Globale",
    you_got_a_challenge_from : "Sei stato sfidato da",
    accept : "Accetta",
    game_over : "Game Over",
    ok : "Ok",
    you_won : "Hai vinto!",
    you_lost : "Hai perso!",
    your_opponent_left_the_game : "(Il tuo avversario ha abbandonato la partita)",
    miss : "mancato!",
    dodge : "schivata!",
    critical : "critico!",
    ready : "Pronto, via!",
    health_stat : "Vita",
    attack_stat : "Attacco",
    dodge_stat : "Schivata",
    miss_stat : "Inaccuratezza",
    critical_hit_rate_stat : "Critico"
}